# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_cloneapp', '0002_auto_20190325_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='comments',
        ),
    ]
