# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_cloneapp', '0005_auto_20190325_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post',
            field=tinymce.models.HTMLField(default=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='picture/'),
        ),
    ]
