# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_cloneapp', '0006_auto_20190325_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(upload_to='pic/'),
        ),
    ]
