# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_cloneapp', '0012_auto_20190327_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='like',
            new_name='likes',
        ),
    ]
