# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_cloneapp', '0013_auto_20190327_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='comments',
        ),
    ]
